{% set name = "apache-airflow-providers-exasol" %}
{% set version = "4.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-exasol-{{ version }}.tar.gz
  sha256: e7e7439c5073c1ca86e8ab8aa88a93a552be68a18851970d7ad28e3b85371ed9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - apache-airflow-providers-common-sql >=1.3.0
    - apache-airflow >=2.3.0
    - pandas >=0.17.1
    - pyexasol >=0.5.1

test:
  imports:
    - airflow.providers.exasol
    - airflow.providers.exasol.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-exasol package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-exasol/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
