{% set name = "apache-airflow-providers-exasol" %}
{% set version = "4.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_exasol-{{ version }}.tar.gz
  sha256: 294d50c350bd7f76bb63bfce3728464744d9cef4729713aa9539d8725a3d5e52

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow-providers-common-sql >=1.10.0
    - apache-airflow >=2.6.0
    - pandas >=1.2.5,<2.2
    - pyexasol >=0.5.1

test:
  imports:
    - airflow.providers.exasol
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-exasol for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/exasol/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-exasol/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
