{% set name = "apache-airflow-providers-exasol" %}
{% set version = "4.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_exasol-{{ version }}.tar.gz
  sha256: f29c653998d7bc4fd931cc045059022c401bd81f9f1e81fb75779b604d74cf26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8,<4.dev0
    - apache-airflow-providers-common-sql >=1.14.1
    - apache-airflow >=2.8.0
    # # the more restrictive constraint to stay noarch: python
    # https://github.com/apache/airflow/blob/providers-exasol/{{ version }}/generated/provider_dependencies.json
    - pandas >=2.1.2,<2.2
    - pyexasol >=0.5.1

test:
  imports:
    - airflow.providers.exasol
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-exasol for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/exasol/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-exasol/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
