{% set name = "apache-airflow-providers-exasol" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-exasol-{{ version }}.tar.gz
  sha256: 80f5262cbd9d0338282bffd2b7f4c8a5bb594fb574f90072c936e9271376026e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - apache-airflow >=2.1.0
    - pandas >=0.17.1,<1.4
    - pyexasol >=0.5.1,<1.0.0

test:
  imports:
    - airflow.providers.exasol
    - airflow.providers.exasol.hooks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Exasol for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-exasol/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
