{% set name = "apache-airflow-providers-exasol" %}
{% set version = "4.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_exasol-{{ version }}.tar.gz
  sha256: 751f4f7f74744ccf3d6922bb83296d3a870f123da601cfd0dfca4dc06cee8a87

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - apache-airflow-providers-common-sql >=1.26.0
    - pyexasol >=0.5.1
    # # the more restrictive constraint to stay noarch: python
    # https://github.com/apache/airflow/blob/providers-exasol/{{ version }}/generated/provider_dependencies.json
    - pandas >=2.1.2,<2.2

test:
  imports:
    - airflow.providers.exasol
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-exasol for Apache Airflow
  license: Apache-2.0
  license_family: Apache
  license_file: src/airflow/providers/exasol/LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-exasol/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
